language: c
compiler:
- gcc
- clang
install:
- sudo apt-get update
- sudo apt-get install -y check libsubunit0 libsubunit-dev
before_script:
- mkdir build
- cd build
- cmake ..
script: make && ctest -V
